### ISSUE TITLE
Подрезал класс

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#10]
В целом с селекторами странно в этом проекте
Где то жестко к классу, где то к классу + части текста, где то к части класса - хотя класс везде один и тот же.

Просто это может вызвать путаницу и вопросы при доработках, сделано так специально из за особенности сайта или по хотелке человека. Лучше придерживаться какого то одного формата селекторов по сайту имхо

Шаг: 17f45ff1-8e44-4e6e-a6a2-aa1f08f901d5

**Comment by NIBugakov** [comment]
короче я бы по поводу селекторов в дискорде проговорил

**Comment by aademid** [comment]
Аналогично - https://github.com/NIBugakov/PIX_riwGosh/issues/8
