### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#11]
Так себе регулярка + не отработает если указать число с одной цифрой, например "4"

Так себе, т.к. у тебя грубо говоря две регулярки записаны в одну... Спорно, я бы так не делал, разбил уже на 2 шага парсинга, имхо - перегружает код для понимания.

Шаг: baa0472c-8b39-4ecd-88f2-02a3eb7fea5e

**Comment by NIBugakov** [comment]
![image](https://github.com/NIBugakov/PIX_riwGosh/assets/159261560/eb70b27a-2fd1-4bb0-86af-a47829d4bfe9)
исправил

**Comment by NIBugakov** [comment]
ну хз ,не вижу смысла разбивать на два ,просто тут происходит одна логика

**Comment by aademid** [comment]
> ![image](https://private-user-images.githubusercontent.com/159261560/307845532-eb70b27a-2fd1-4bb0-86af-a47829d4bfe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjIyNjYsIm5iZiI6MTcwODk2MTk2NiwicGF0aCI6Ii8xNTkyNjE1NjAvMzA3ODQ1NTMyLWViNzBiMjdhLTJmZDEtNGJiMC04NmFmLWE0NzgyOWQ0YmZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTM5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVkMjc0ZTAyNzU0NTgzMGNhMDc0Y2U3OGZmNDIwM2UxZmFhZjdhMDJkOTJjZDE2YTlhNTYzYjkxZDViNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xmBej5xjLqSHzYuxHfTBN5KwMuKbOCq2Yvw-m8gGdBs) исправил

+ в квадратных скобках [,.] - буквально - запятая или любой символ

**Comment by aademid** [comment]
> > ![image](https://private-user-images.githubusercontent.com/159261560/307845532-eb70b27a-2fd1-4bb0-86af-a47829d4bfe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjIyNjYsIm5iZiI6MTcwODk2MTk2NiwicGF0aCI6Ii8xNTkyNjE1NjAvMzA3ODQ1NTMyLWViNzBiMjdhLTJmZDEtNGJiMC04NmFmLWE0NzgyOWQ0YmZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTM5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVkMjc0ZTAyNzU0NTgzMGNhMDc0Y2U3OGZmNDIwM2UxZmFhZjdhMDJkOTJjZDE2YTlhNTYzYjkxZDViNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xmBej5xjLqSHzYuxHfTBN5KwMuKbOCq2Yvw-m8gGdBs) исправил
> 
> * в квадратных скобках [,.] - буквально - запятая или любой символ

Отмена, . в скобках квадратных ищет только точку. Я думал что\ \. надо указывать

**Comment by aademid** [comment]
Исправлено caedce49f02e118f286b4db966b8456f1ce37db0
Обсудили возможные варианты
