### ISSUE TITLE
"aria-haspopup" в селекторе

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#12]
Тег довольно редко встречается, точнее первый раз вижу

Обычно более предпочтительные какие то более распространенные - role, class и т.п.
Шаг: 278910ce-94a7-4d6b-8f59-b845b2830090

**Comment by NIBugakov** [comment]
чувствую это работа требует дискуссии

**Comment by aademid** [comment]
Обсудили - исправлять не стал
Решение рабочее, вопрос надежности - индивидуален caedce49f02e118f286b4db966b8456f1ce37db0
