### ISSUE TITLE
Клик не по веб элементу?

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#4]
Думаю можно клик "Веб" но не программный - эффект должен быть такой же.
Есть ощущение - что есть возможность избежать привязки к "РИВ ГОШ", возможно даже в этом селекторе?

Хотя в целом селектор лояльный, даже о браузере подумал. 

Я обычно оставляю браузер в селекторе, а к названиям вкладок не цепляюсь.
Одно из предыдущих заданий, где меняли браузер - было исключительно для тренировки.
Когда нет возможности зацепиться вебом, то в UI селекторах можно оставлять куски браузера (тут без понятия что стабильнее, скорее всего браузер чем название вкладки сайта).

Шаг: 94a77405-2144-4498-b122-889cf46cc643

**Comment by NIBugakov** [comment]
Хз иного мнения ,с учетом ,что мы работаем с конкретным сайтом

**Comment by aademid** [comment]
> Хз иного мнения ,с учетом ,что мы работаем с конкретным сайтом

Тут больше вопрос о том что вероятнее поменяется
Используемый браузер или обновление сайта. Как будто сайт более вероятен, браузер разве что сам вручную - но тогда много чего может полететь. 
Очень редко роботы настолько круто написаны что браузер меняется и в его смене есть необходимость.
Если с селектором еще согласен, то с активностью UI - жду комента либо исправления

**Comment by aademid** [comment]
Тут скорее не прервать цикл а ошибка - т.к. робот за 100 итераций не сделал что хотел
Шаг: 4b42e635-5be0-4905-9dfa-200b041ffc69
