### ISSUE TITLE
Селектор (очень страшно, не знаю что ето такое, как ты ето сделал вообще)

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#5]
Он у меня даже не отработал без корректировки

Шаг: 5855f89d-c9e9-4c18-abb1-fb2d0285c7f6

**Comment by NIBugakov** [comment]
Опять же хз ,как это сюда попало ,опять же она даже отрабатывало ,ну я переделал

**Comment by aademid** [comment]
Исправлено - caedce49f02e118f286b4db966b8456f1ce37db0
