### ISSUE TITLE
Логика 

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#6]
Пагинация страниц не везде есть, тоже не отработал селектор на бренде AXE (т.к. там нет страниц)

Шаг: c0d58b7f-1f93-46cc-9c49-e1bc8cc6b138

**Comment by NIBugakov** [comment]
Могу ли я просто тогда включить пропустить при ошибке ,или обязательно или менять таргет на что-то другое?

**Comment by aademid** [comment]
> Могу ли я просто тогда включить пропустить при ошибке ,или обязательно или менять таргет на что-то другое?

Ощущение что эта активность вообще не нужна

**Comment by aademid** [comment]
> Могу ли я просто тогда включить пропустить при ошибке ,или обязательно или менять таргет на что-то другое?

А, дальше логика тоже на страницах подвязана...
Лучше поменять таргет\логику немного тогда

Шаг: 4a8958fc-4544-4386-a67d-23ab5525bceb

**Comment by NIBugakov** [comment]
ну так-то да ,но если допустим пропустить при ошибке(ну или проверить существование) ,тогда он до следующей логики не дойдет ,так как это одиночная страница и он просто переходом на ссылку прогрузит все товары имеющиеся

**Comment by NIBugakov** [comment]
плюс к этому он не зайдет в цикл ,что тоже с время выиграет

**Comment by aademid** [comment]
Элемент остался, обсудили варианты решения проблемы
Учет на будущее, в данном проекте исправлять не надо
