### ISSUE TITLE
Селектор 

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#8]
Просто привязаться к тексту кажется проще\надежнее
Шаг: 5e18e7d6-6070-4cd7-8c22-d93ddd828312

**Comment by aademid** [comment]
> Просто привязаться к тексту кажется проще\надежнее Шаг: 5e18e7d6-6070-4cd7-8c22-d93ddd828312

ну либо только к классу, а то дальше по коду вижу привязку жестко к классу, что в целом оправдано

**Comment by aademid** [comment]
С цветом тоже самое 
Шаг: 9ae1d4f4-7349-4642-bdbf-4a954beae820

**Comment by aademid** [comment]
И наличие онлайн
Шаг: 824159ea-9805-4d62-903a-d74934fb74fa

**Comment by aademid** [comment]
И "В других городах"
Шаг: b13ca2e5-5a2f-4461-b204-450474853557

**Comment by NIBugakov** [comment]
Честно не считаю плохими селекторами ,местами даже более надежными ,исключительно к тексту вязаться ну хз

**Comment by NIBugakov** [comment]
а без текста менее читаемые и надежные

**Comment by aademid** [comment]
Обсудили, пришли к выводу что способ построение селекторов - индивидуальная история
Оставили без изменений, рассмотрели разные вариации построения селекторов
