### ISSUE TITLE
Коменты вида "/////////////////////////////////"

### ISSUE THREAD

**Issue by aademid** [NIBugakov/PIX_riwGosh#9]
Личное мнение: Не очень красиво\бесмыслено

Если требуется просто место занять, можно Enter клацнуть в активности "Комментарий"

**Comment by NIBugakov** [comment]
Ну я бы отсавли бы так ,ну или так 
![image](https://github.com/NIBugakov/PIX_riwGosh/assets/159261560/30ba6375-6b52-4b5e-8fe7-7462f601f043)

**Comment by aademid** [comment]
> Ну я бы отсавли бы так ,ну или так ![image](https://private-user-images.githubusercontent.com/159261560/307850726-30ba6375-6b52-4b5e-8fe7-7462f601f043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjIxNTYsIm5iZiI6MTcwODk2MTg1NiwicGF0aCI6Ii8xNTkyNjE1NjAvMzA3ODUwNzI2LTMwYmE2Mzc1LTZiNTItNGI1ZS04ZmU3LTc0NjJmNjAxZjA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2U5NmYwNjM2MzU1N2UyYTM5MzhhYzM5YjQ1ZDJlNjIzYWVkZTI2MTc4MGNiMzZmNTQ3ZjVhMmRmN2Y1NDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z0iFQCzkR3XCPTLkwgEMGM_dWBT6t8kkd6pHzfy-Vms)

Ну это уже кому как нравится, просто ///////////////////////// выглядит как оставшийся кусок после конвертера, визуально мало что дает, линия хоть как то минималистично\красиво)

Снял тэг "Незначительно" , это больше индивидуальность на обсуждение а не замечание

**Comment by aademid** [comment]
Индивидуальность
